### ISSUE TITLE
License Legality

### ISSUE THREAD

**Issue by aatxe** [cusspvz/pol#1]
Are you a lawyer, by any chance?

**Comment by kylevedder** [comment]
If you are not a lawyer, then anyone using this license faces unintended use of their code or potentially a lawsuit. If that is the case, you should state in your README that you are not a lawyer and that users should use at their own risk.

To drive home this point, the first sentence in the license is not grammatically correct.

**Comment by cusspvz** [comment]
Thanks for noticing it.

Indeed I am not. I've built this license for having private software modules exposed to the public implicit usage.

It would be awesome if you both wish to contribute to it, or arrange someone who could be interested to do so. 😃 

Thanks,
José Moreira
